django/apps/register/urls.py
from django.urls import path

from . import views
app_name = 'accounts'
urlpatterns = [
    path('', views.index,name='index'),
    path('register/', views.register,name='register'),
    path('success/', views.success),
    path('login/', views.user_login,name='login'),
    path('list/', views.list),
    path('logout/', views.user_logout, name ='logout')
]

django/login_registration/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from login_registration import settings

from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.register.urls')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/apps/register/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

from django.db.models import CASCADE


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE)

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.user.username

django/apps/register/forms.py
from django import forms
from django.contrib.auth.models import User

from apps.register.models import UserProfile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email", "password",]


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('first_name','last_name')

django/apps/register/views.py
from django.contrib.auth.decorators import login_required

from apps.register.forms import UserForm, UserProfileForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.contrib.auth import authenticate, login
from django.shortcuts import render, HttpResponse, redirect, render_to_response
from django.contrib import messages
from django.template import RequestContext

from .models import User

def list(request):
    return render(request, 'products/list.html')
def index(request):
    return render(request, 'index.html')


def register(request):

    registered = False
    if request.method == 'POST':
        uform = UserForm(data=request.POST)
        pform = UserProfileForm(data=request.POST)
        if uform.is_valid() and pform.is_valid():
            user = uform.save()
            # form brings back a plain text string, not an encrypted password
            pw = user.password
            # thus we need to use set password to encrypt the password string
            user.set_password(pw)
            user.save()
            profile = pform.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
            return render(request,'index.html')
        else:
            print(uform.errors, pform.errors)
    else:
        uform = UserForm()
        pform = UserProfileForm()

    return render_to_response('accounts/signup.html', {'uform': uform, 'pform': pform, 'registered': registered}, RequestContext(request, {}))


# def register(request):
#     if request.method == 'POST':
#
#         errors = User.objects.validator(request.POST)
#         if len(errors):
#             for tag, error in errors.iteritems():
#                 messages.error(request, error, extra_tags=tag)
#             return redirect('/')
#
#         hashed_password = request.POST['password']
#         user = User.objects.create(first_name=request.POST['first_name'], last_name=request.POST['last_name'], password=hashed_password, email=request.POST['email'])
#
#         user.save()
#         request.session['id'] = user.id
#         authenticate(request, id=user.id)
#         return redirect('/success')
#     else:
#        return render(request,'accounts/signup.html')
#

# def log_in(request):
#     if request.method == 'POST':
#
#         if (User.objects.filter(email=request.POST['login_email']).exists()):
#             user = User.objects.filter(email=request.POST['login_email'])[0]
#             print(user.email)
#             if (request.POST['login_password']==user.password):
#                 request.session['id'] = user.id
#                 authenticate(request, email=user.email,password=user.password)
#
#                 return redirect('/success')
#         c = {
#             "error": 'Wrong email or password'
#         }
#         return render(request,'accounts/login.html',context=c)
#     else:
#         return render(request, 'accounts/login.html')


from django.contrib.auth import authenticate, login, logout


def user_login(request):
    context = RequestContext(request)
    if request.method == 'POST':
          username = request.POST['username']
          password = request.POST['password']
          user = authenticate(username=username, password=password)
          if user is not None:
              if user.is_active:
                  login(request, user)

                  return render(request,'index.html')
              else:

                  return HttpResponse("You're account is disabled.")
          else:

              print ( "invalid login details " + username + " " + password)
              return render_to_response('accounts/login.html', {}, context)
    else:

        return render_to_response('accounts/login.html', {}, context)

def success(request):
    user = User.objects.get(id=request.session['id'])
    context = {
        "user": user
    }
    return render(request, 'register/success.html', context)

@login_required
def user_logout(request):
    context = RequestContext(request)
    logout(request)
    # Redirect back to index page.
    return render(request, 'index.html')

django/apps/register/templates/register/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body><h1>Welcome, <strong>{{user.first_name}} {{user.last_name}}</strong></h1>
  {{ request.user.username }}
</body>
</html>

django/apps/register/templates/register/oldindex.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Email Validation</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"> {% load static %}
    <link rel="stylesheet" href="{% static 'register/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
        crossorigin="anonymous">
</head>

<body>
 <p>Welcome, <strong>{{request.user.first_name}} {{request.user.last_name}}</strong></p>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-4">
                <div class="card">
                    <h4 class="card-header text-center">Register</h4>
                    <div class="card-block">
                        <form method="post" action="/register">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>First Name</label>
                                <input name="first_name" type="text" class="form-control form-control-danger"> 
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "first_name" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="form-control-feedback">{{message}}</div>
                                  </div>
                                {%endif%} {%endfor%} {% endif %}
                            </div>
                            <div class="form-group">
                                <label>Last Name</label>
                                <input name="last_name" type="text" class="form-control">
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "last_name" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="form-control-feedback">{{message}}</div>
                                  </div>
                                {%endif%} {%endfor%} {% endif %}
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <input name="email" type="email" class="form-control">
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "email" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="form-control-feedback">{{message}}</div>
                                  </div>
                                {%endif%} {%endfor%} {% endif %}
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input name="password" type="password" class="form-control">
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "password" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="form-control-feedback">{{message}}</div>
                                  </div>
                                {%endif%} {%endfor%} {% endif %}
                            </div>
                            <div class="form-group">
                                <label>Confirm Password</label>
                                <input name="confirm_password" type="password" class="form-control">
                                {% if messages %} 
                                {%for message in messages %} 
                                {%if "confirm_password" in message.tags %}
                                <div class="form-group has-danger">
                                    <div class="form-control-feedback">{{message}}</div>
                                  </div>
                                {%endif%} {%endfor%} {% endif %}
                            </div>
                            <div class="mx-auto text-center">
                                <input type="submit" value="Create Account" class="btn btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card">
                    <h4 class="card-header text-center">Login</h4>
                    <div class="card-block">
                        <form method="post" action="/login">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Email</label>
                                <input name="login_email" type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input name="login_password" type="password" class="form-control">
                            </div>
                            <div class="mx-auto text-center">
                                <input type="submit" value="Login" class="btn btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </script>
</body>

django/apps/register/templates/register/success.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Success</title>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'register/style.css' %}">
	<meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-8">
				<div class="alert alert-success" role="alert'">
					<h4 class="alert-heading">Success</h4>
                        <p>Welcome, <strong>{{user.first_name}} {{user.last_name}}</strong></p>
                    {% if user.is_authenticated %}
                    logged in
                    {% endif %}
				</div>
			</div>
		</div>
	</div>
</body>
</html>

django/templates/accounts/login.html
<!DOCTYPE HTML>{% load staticfiles %}
<html>
    <head>
         

    </head>
<body>
    



  <form method = "post" class="modal-content animate" >
    <div class="imgcontainer">
      
      <img src={% static "assets/images/img_avatar2.png" %} alt="Avatar" class="avatar">
    </div>

    <div class="container">
     <form method="post" >
 {% csrf_token %}
                            <div class="form-group">
                                <label>Username</label>
                                <input name="username" type="text" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input name="password" type="password" class="form-control">
                            </div>
                            <div class="mx-auto text-center">
                                <input type="submit" value="Login" class="btn btn-primary">
                            </div>
                        </form>
    </div>
  </form>

      <div class="container" style="background-color:#f1f1f1">
          <a href="index.html"><button type="button" class="cancelbtn">Cancel</button></a>

    </div>

    {% if error %}{{ error }}{% endif %}



    
    
    </body>
</html>

django/templates/accounts/signup.html
<!DOCTYPE html>
<html>

<body>





  <form method ="post" class="modal-content" enctype="multipart/form-data" >
  {% csrf_token %}
    <div class="container">
      <h1>Sign Up</h1>
      <p>Please fill in this form to create an account.</p>
      <hr> <div class="form-group">
      {% for field in uform.visible_fields %}
    {{ field.label }}
    {{ field }}
    {% endfor %}
      {% for field in pform.visible_fields %}
    {{ field.label }}
    {{ field }}
{% endfor %}
    </div>
{#      <div class="form-group">#}
{#          <label for="First Name"><b>First Name</b></label>#}
{#                              {{ pform.first_name }}#}
{#                            </div>#}
{#                            <div class="form-group">#}
{#                                <label for="Last Name">Last Name</label>#}
{#                               {{ pform.last_name }}#}
{#                            </div>#}
{#                             <div class="form-group">#}
{#                                <label for="email">Email</label>#}
{#                                 <div class="form-group">{{ uform.email }}</div>#}
{#                            </div>#}
{#                            #}
{#                            <div class="form-group">#}
{#                                 <label for="password"><b>Password</b></label>#}
{#                               {{ uform.password }}#}
{#                            </div>#}
{#                        <div class="form-group">#}
{#                                 <label for="password"><b>username</b></label>#}
{#                               {{ uform.username }}#}
{#                            </div>#}


      <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>

      <div class="clearfix">
        <a href="index.html"><button type="button" class="cancelbtn">Cancel</button></a>
        <button type="submit" class="signupbtn">Sign Up</button>
      </div>
    </div>
  </form>


<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

</body>
</html>

django/templates/index.html
<!DOCTYPE HTML>


{% load staticfiles %}

<html>
	<head>
		<title>Index</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

	</head>
	<body class="landing is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<header id="header" class="alt">

					<nav id="nav">
						<ul>
							<li><a href="{% url 'accounts:index' %}">Home</a></li>
                            <li><a href="">Post  {{ user.username }}</a></li>

							<li>
								<a href="#" class="icon fa-angle-down">Layouts</a>
								<ul>




                            {%  if user.is_authenticated %}
                            <li> <a href="{% url 'accounts:logout' %}" class="button">Logout</a></li>
                            {% else %}
							<li><a href="{% url 'accounts:login' %}" class="button">Login</a></li>
                            {% endif %}
						</ul>
					</nav>
				</header>

			<!-- Banner -->
				<section id="banner">

					<ul class="actions special">
                        {%  if user.is_authenticated %}
                            <li><a href="{% url 'accounts:register' %}" class="button primary">Post AD</a></li>
                        {% else %}
						<li><a href="{% url 'accounts:register' %}" class="button primary">Sign Up</a></li>
                        {% endif %}
						<li><a href="#" class="button">Learn More</a></li>
					</ul>
                    
				
				</section>

	</body>
</html>